import Head from "next/head"
import Nav from "../components/NavBar"

export default function Home() {
  return (
    <div className="bg-gradient-to-br from-violet-900 to-fuchsia-800 h-screen w-screen">
      <div className="bg-black bg-opacity-25 h-screen w-screen">
        <Head>
          <title>TDW MP2 Pedro Miguel Pereira</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
      </div>
    </div>
  )
}
