import Head from "next/head"
import Nav from "../components/NavBar"
import Jumbotron from "../components/Jumbotron"
import Search from "../components/Search"
import Row from "../components/Row"
import { useState, useEffect } from "react"
import {
  useGetTrendingTitlesQuery,
  useGetMovieQuery,
} from "../features/TMDB_API/moviesSlice"

export default function Home() {
  const [searchBar, setSearchBarState] = useState(false)

  const onKeyDown = e => {
    if ((e.metaKey && e.key === "k") || (e.metaKey && e.key === "K")) {
      setSearchBarState(true)
    }
  }

  useEffect(() => {
    document.addEventListener("keydown", onKeyDown)

    return () => {
      document.removeEventListener("keydown", onKeyDown)
    }
  }, [])

  return (
    <div className="bg-slate-800">
      <Head>
        <title>TDW MP2 Pedro Miguel Pereira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black bg-opacity-25">
        {searchBar && <Search setSearchBarState={setSearchBarState} />}
        <Nav setSearchBarState={setSearchBarState} />
        <Jumbotron />
        <Row rowTitle="Nos cinemas" request={useGetMovieQuery("now_playing")} />
        <Row rowTitle="Tendências" request={useGetMovieQuery("popular")} />
        <Row rowTitle="Brevemente" request={useGetMovieQuery("upcoming")} />
        <Row rowTitle="Mais Votados" request={useGetMovieQuery("top_rated")} />
        <Row
          rowTitle="Filmes em Destaque"
          request={useGetTrendingTitlesQuery({
            type: "movie",
            time_window: "day",
            page: "1",
          })}
        />
        <Row
          rowTitle="Séries em Destaque"
          request={useGetTrendingTitlesQuery({
            type: "tv",
            time_window: "day",
            page: "1",
          })}
        />
      </main>
    </div>
  )
}
